sudo: required

language: go

services:
  - docker

script:
  - go build .
  - docker build -t ezgliding/crawler:$TRAVIS_COMMIT .

after_success:
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
    docker tag ezgliding/crawler:$TRAVIS_COMMIT ezgliding/crawler:$TRAVIS_TAG
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      docker push ezgliding/crawler:$TRAVIS_TAG
    fi
